name: Build Blue.dll and Blender Addon

on:
  push:
    branches: [ update-build ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      STEAM_USER: ${{ secrets.STEAM_USER }}
      STEAM_PASS: ${{ secrets.STEAM_PASS }}
      RESONITE_HEADLESS_KEY: ${{ secrets.RESONITE_HEADLESS_KEY }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Cache Resonite installation
      id: cache-resonite
      uses: actions/cache@v4
      with:
        path: dependencies/resonite
        key: resonite-${{ runner.os }}-headless-${{ hashFiles('scripts/download-resonite.sh') }}
        restore-keys: |
          resonite-${{ runner.os }}-headless-

    - name: Download Resonite Headless
      if: steps.cache-resonite.outputs.cache-hit != 'true'
      run: bash scripts/download-resonite.sh

    - name: Prepare Blue.csproj
      run: |
        sed 's|\$BLESONITE_HEADLESS|../../dependencies|g' src/Blue/Blue.csprojtemplate > src/Blue/Blue.csproj

    - name: Build Blue.cs
      run: |
        dotnet build src/Blue/Blue.csproj --configuration Release

    - name: Copy DLL into Blender Addon
      run: |
        mkdir -p src/Python/blue_blender_addon
        cp src/Blue/bin/Release/net8.0/Blue.dll src/Python/blue_blender_addon/

    - name: Zip Blender Addon
      run: |
        cd src/Python
        zip -r blessonite-blender.zip blue_blender_addon

    - name: Upload Blue.dll Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Blue.dll
        path: src/Blue/bin/Release/net8.0/Blue.dll

    - name: Upload Blender Addon ZIP
      uses: actions/upload-artifact@v4
      with:
        name: blue_blender_addon.zip
        path: src/Python/blessonite-blender.zip

    - name: Create GitHub Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: |
          src/Blue/bin/Release/net8.0/Blue.dll
          src/Python/blessonite-blender.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
